<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:variable name="initial_bottom_pos">0.0</xsl:variable>
	<xsl:variable name="initial_left_pos">0.5</xsl:variable>
	<xsl:variable name="height_increment">0.0</xsl:variable>
	<xsl:variable name="width_increment">0.0</xsl:variable>
	<xsl:variable name="frame_height">2.5cm</xsl:variable>
	<xsl:variable name="frame_width">8.3cm</xsl:variable>
	<xsl:variable name="number_columns">1</xsl:variable>
	<xsl:variable name="max_frames">1</xsl:variable>

	<xsl:template match="/">
		<xsl:apply-templates select="lots"/>
	</xsl:template>

	<xsl:template match="lots">
		<document>
			<template pageSize="9cm,2.9cm" leftMargin="0.5cm" rightMargin="0.5cm" topMargin="0.5cm" bottomMargin="0.5cm" title="Label list" author="Generated by CubicERP">
				<pageTemplate id="all">
					<pageGraphics/>
					<xsl:apply-templates select="lot-line" mode="frames"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<paraStyle name="nospace" fontName="Courier" fontSize="10" spaceBefore="0" spaceAfter="0"/>
				<blockTableStyle id="mytable">
					<blockBackground colorName="white" start="0,0" stop="0,0"/>
					<blockBackground colorName="white" start="1,0" stop="-1,0"/>
					<blockAlignment value="CENTER"/>
					<blockValign value="MIDDLE"/>
					<blockFont name="Helvetica-BoldOblique" size="14" start="0,0" stop="-1,0"/>
					<blockFont name="Helvetica" size="8" start="0,1" stop="-1,1"/>
					<lineStyle kind="GRID" colorName="black" tickness="1"/>
				</blockTableStyle>
			</stylesheet>
			<story>
				<xsl:apply-templates select="lot-line" mode="story"/>
			</story>
		</document>
	</xsl:template>

	<xsl:template match="lot-line" mode="frames">
		<xsl:if test="position() &lt; $max_frames + 1">
			<frame>
				<xsl:attribute name="width">
					<xsl:value-of select="$frame_width"/>
				</xsl:attribute>
				<xsl:attribute name="height">
					<xsl:value-of select="$frame_height"/>
				</xsl:attribute>
				<xsl:attribute name="x1">
					<xsl:value-of select="$initial_left_pos + ((position()-1) mod $number_columns) * $width_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
				<xsl:attribute name="y1">
					<xsl:value-of select="$initial_bottom_pos - floor((position()-1) div $number_columns) * $height_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
			</frame>
		</xsl:if>
	</xsl:template>

    <xsl:param name="pmaxChars" as="xs:integer" select="80"/>

	<xsl:template match="lot-line" mode="story">
            <blockTable style="mytable" colWidths="4.0cm,3.3cm">
                <tr>
                    <td>
                        <para style="nospace"><xsl:value-of select="code"/></para>
                    </td>
                    <td>
                        <para style="nospace" t="1"><xsl:value-of select="price"/><xsl:text>  </xsl:text><xsl:value-of select="currency"/></para>
                    </td>
                </tr>
                <tr>
                    <td>
                        <barCode  x="0cm" y="0cm" quiet="0" barWidth="0.7" ><xsl:value-of select="ean13" /></barCode> 
                    </td>
                    <td>
                        <para style="nospace"><xsl:value-of select="substring(product, 1, $pmaxChars)"/></para><xsl:text>, </xsl:text>
                        <para style="nospace"><xsl:value-of select="variant"/></para>
                    </td>
                </tr>
            </blockTable>
	<nextFrame/>
	</xsl:template>
</xsl:stylesheet>
